spring:
  main:
    web-application-type: none
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:20093/xxl-job-admin
    executor:
      address: ''
      appname: xxl-job-executor-main
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 20094